### ISSUE TITLE
首次查询必须要刷新一下页面，才会加载查询结果

### ISSUE THREAD

**Issue by codebug111** [uiuing/VARBook#10]
首次查询必须要刷新一下页面，才会加载查询结果。

**Comment by uiuing** [comment]
您好，是否有更详细的描述，这种情况很难复现，在输入内容之后回车显示结果，并没有发现问题

**Comment by codebug111** [comment]
![image](https://user-images.githubusercontent.com/37678387/183800745-f8c179a3-9194-457d-892b-d8d3681427a5.png)

**Comment by uiuing** [comment]
感谢反馈，问题已经解决了，貌似是后端缓存导致的问题。THK @codebug111

**Comment by codebug111** [comment]
现在首次打开值是空的就会提示 warning   请求过短，至少2个纯数字以外的字符
 
 
 
 
 
 
 
 
 
 
 

  -- 
 
 
 发自新浪邮箱客户端 
 
 
  
  在 8月10日 14:15，uiuing ***@***.***> 写道： 
   
  感谢反馈，问题已经解决了，貌似是后端缓存导致的问题。THK @codebug111

**Comment by uiuing** [comment]
当然如此，如果你没有值，htpps://varbook.uiuing.com/#{value}
