### ISSUE TITLE
一个小建议

### ISSUE THREAD

**Issue by cloudmoonocus** [uiuing/VARBook#12]
看了源码和网站实际使用，发现作者是这么做的：
- 默认是搜索后自动复制小驼峰，如果这时复制其他类型，localstore会自动更改下次复制的命名类型，下一次再搜索会自动复制该类型，而不是默认的小驼峰。
所以就是我想建议作者在tips这里添加一个提示，例如：
![image](https://user-images.githubusercontent.com/98140702/183250223-6f44b2b1-a724-4d40-8448-0c25ee5df2c7.png)
这里我把下面那段自动切换代码也改了

**Comment by uiuing** [comment]
@cloudmoonocus  感谢您的反馈～，您可以直接提交pr哦

**Comment by uiuing** [comment]
当然我也会修改的，感谢反馈
