### ISSUE TITLE
超出没有出现滚动条，看不到下面的东西，必须缩放浏览器比例 ， 按回车不自动搜索，   必须得点搜索icon

### ISSUE THREAD

**Issue by mobuxi2** [uiuing/VARBook#9]
![image](https://user-images.githubusercontent.com/93361622/179492494-2a494a23-491a-40a8-8391-ded2cc53ada2.png)

**Comment by uiuing** [comment]
感谢您的反馈，搜索快捷键现在已修改为Enter

**Comment by uiuing** [comment]
已修复，感谢您的反馈！ @mobuxi2
